#!/bin/bash
ARGS="$@:2"

case $1 in
"serve")
    php -S localhost:8000 -t public
;;
"migrate")
    php artisan migrate
;;
"migrate:fresh")
    php artisan migrate:fresh
;;
*)
    echo Unexpected argument: $1
    exit 1
;;
esac
